Use HTTPS for instances that support it
freedomofpress/securedrop-https-everywhere-ruleset pull request #153
Opened 2024-01-12 20:08 UTC by legoktm

### Status

Work in Progress (not signed)

### Description

For instances that already redirect to HTTPS, have our ruleset also
point to HTTPS, avoiding one extra HTTP->HTTPS redirect.
    
Since this information isn't available from the directory, make requests
to the instances themselves and see if they try to redirect to HTTPS.
For simplicity, we use Tor Browser's internal SOCKS proxy, so it needs
to be running in the background.
    
Fixes #4.

### Review Checklist

- [ ] Changes to `onboarded.txt` are accurate
- [ ] The file `default.rulesets.TIMESTAMP.gz` has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [ ] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to `Path Prefix`: `https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME`
- [ ] `index.html` has been updated using `./update_index.sh`

### Post-Deployment Checklist

- [ ] Added/modified onion names have been updated in the SecureDrop Directory

2024-01-12 20:40 UTC, legoktm commented
A far simpler approach would be to add a `https` column to `onboarded.txt` and use that. I initially dismissed that but given there are just 2 instances that need it, it seems pretty straightforward to maintain.

2024-01-17 16:33 UTC, zenmonkeykstop requested changes

2024-01-17 19:35 UTC, legoktm commented on sddir.py
> +# Use Tor Browser's internal SOCKS proxy
That was my intention, but no longer in the `onboarded.txt` version.

2024-01-17 19:39 UTC, legoktm commented
Now updated to store and pull data from onboarded.txt instead of doing live checking.

2024-01-24 19:55 UTC, zenmonkeykstop commented
Confirmed that the ruleset changes look consistent with the https option. A new signed ruleset has been added in a separate commit. Final review to follow to verify the rules work in TBB as expected.

2024-01-24 20:16 UTC, zenmonkeykstop commented
(handing off to @nathandyer for live ruleset checks)

2024-01-24 21:07 UTC, nathandyer approved these changes
Happy to report everything worked correctly for me in the live tests, and that the Source Interfaces loaded using HTTPS.

Just a note about the test plan, no changes should be necessary in the directory itself.

2024-01-24 21:11 UTC, merged