Split generate and sign steps; add more CI checks
freedomofpress/securedrop-https-everywhere-ruleset pull request #202
Opened 2024-09-19 21:05 UTC by legoktm

### Status

Ready for review

### Description

One of the biggest frustrations I have with this process is that the
generation and signing steps are combined. I really want to generate
everything, review it, and then move ahead with signing.

This splits the two steps and inlines them into the Makefile as separate
`make generate` and `make sign`. Also change the default goal to `help`,
which is what all of our other Makefiles do.

This necessitates checking in the default.rulesets file that's used as
the input for signing.

As requested in #21, this verifies:

* generated rulesets files match the XML files. (In some sense it's just
  a reimplementation of the `upstream/merge-rulesets.py` script, but would
  stop a zero-length ruleset from being deployed)
* there are no extra nor missing signatures

Fixes #21.

### Review Checklist

* [ ] Visual review
* [ ] CI passes

2024-09-26 17:35 UTC, legoktm commented
Rebased this on top of https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/205, which I used this for. So it works :)

2024-09-30 22:34 UTC, zenmonkeykstop requested changes
Workflow is documented in the README - in the interests of future users' onboarding, the change in the workflow should be documented there too.

2024-09-30 22:39 UTC, legoktm commented
Done!

2024-10-17 17:38 UTC, zenmonkeykstop approved these changes

2024-10-17 17:40 UTC, merged