Add onion name for CNN
freedomofpress/securedrop-https-everywhere-ruleset pull request #86
Opened 2022-03-17 19:16 UTC by conorsch

### Status

Ready for review. Contains two changes:

* Removes iROZHLAS (closes #83)
* Adds CNN (closes #85)

### Review Checklist

- [ ] Changes to `onboarded.txt` are accurate
- [ ] The file `default.rulesets.TIMESTAMP.gz` has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [ ] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to `Path Prefix`: `https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME`
- [ ] `index.html` has been updated using `./update_index.sh`

### Post-Deployment Checklist

- [ ] Added/modified onion names have been updated in the SecureDrop Directory

2022-03-17 20:18 UTC, eloquence commented on rulesets/cnn-securedrop-ruleset.xml
> +    to="http://http://qmifwf762qftydprw2adbg7hs2mkunac5xrz3cb5busaflji3rja5lid.onion" />
Something got borked here @conorsch , accidental protocol duplication?

2022-03-17 20:19 UTC, eloquence requested changes
(CNN ruleset not valid as-is due to protocol duplication)

2022-03-17 20:22 UTC, conorsch commented
Without a doubt, not sure how that happened. Will fix and regenerate.

2022-03-17 20:55 UTC, conorsch commented
The problem only occurs for the CNN entry because the API is returning a protocol for only that entry: 

```
$ curl -s https://securedrop.org/api/v1/directory/ | jq -r '.[].onion_address' | grep http | wc -l
1
```
and the onboarding script assumes there's no protocol on the onion field. 
See related discussion in https://github.com/freedomofpress/securedrop.org/pull/878. While we could easily update the onboarding script to be more forgiving, in this case, I'm going to edit the db entry so that the API returns consistent results across the board. At a later date, we can decide whether we want to enforce stronger validation on that field for future updates.

After updating, I'll regenerate and resign, as stated above.

2022-03-17 21:26 UTC, conorsch commented
@eloquence Updated as described. Please test again, it should work now.

2022-03-17 21:42 UTC, eloquence requested changes
CNN loads for me now, but `irozhlas.securedrop.tor.onion` is still included in the ruleset XML (just removed from `onboarded.txt`), sorry :/

2022-03-17 21:44 UTC, conorsch commented
:facepalm: I never `rm`'d the irozhlas file. Merely removing from onboarding allows the script to complete successfully, but doesn't change the contents of the tarball. Fixing...

2022-03-17 22:45 UTC, conorsch commented
@eloquence Once more, I beseech you: test.

2022-03-18 00:22 UTC, eloquence approved these changes
That did the trick - thanks much :-)

2022-03-18 00:22 UTC, merged